# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pregunta',
            field=models.CharField(choices=[('1', '¿Lugar de Nacimiento de la madre?'), ('2', '¿Nombre de su Mascota?'), ('3', '¿Nombre de la abuela Materna?'), ('4', '¿Plato de comida favorita?')], max_length=100),
        ),
    ]
