# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20170509_0236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
