# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detallecomprobante',
            fields=[
                ('idcomprobante', models.CharField(max_length=20, primary_key=True,serialize=False)),
                ('idproducto', models.CharField(max_length=25)),
                ('cantidad', models.IntegerField()),
                ('importe', models.FloatField()),
            ],
        ),
    ]
