# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detallecomprobante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecomprobante',
            name='idcomprobante',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detallecomprobante',
            name='idproducto',
            field=models.CharField(max_length=20),
        ),
    ]
