# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detallecomprobante', '0002_auto_20170428_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecomprobante',
            name='idproducto',
            field=models.CharField(max_length=25),
        ),
    ]
