# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='idcliente',
            new_name='id_cliente',
        ),
    ]
