# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20170518_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fnacimiento',
            field=models.CharField(max_length=50),
        ),
    ]
