# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fnacimiento', models.DateField()),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
    ]
