# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_empleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='empleado',
        ),
    ]
