# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
        ('presentacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicamento',
            fields=[
                ('id_medicamento', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('nombre_comercial', models.CharField(max_length=50)),
                ('componente', models.CharField(max_length=100)),
                ('concentracion', models.CharField(max_length=50)),
                ('fecha_produccion', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('costo_unidad', models.FloatField()),
                ('venta_unidad', models.FloatField()),
                ('presentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presentacion.presentacion')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
                ('lote', models.CharField(max_length=50)),
                ('estado',models.BooleanField()),
            ],
        ),
    ]
