# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_expiracion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_produccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='tipo',
            field=models.CharField(choices=[('Comercial', 'Comercial'), ('Generico', 'Generico')], max_length=50),
        ),
    ]
